Refactoring and UI updates
benstone1/SocialCademy pull request #27
Opened 2021-09-12 04:37 UTC by john-royal

This includes some feature additions, UI improvements, bug fixes, and some fairly significant refactoring. Some changes might not be agreeable to everyone, so I'm happy to modify this PR as needed.

### Views
* Added ability to view all posts by a certain author from `PostsList`/`PostRow`
* Redesigned `NewPostForm` and relocated from `MainTabView` to a sheet presented from the `PostsList`
* Fixed post titles not being shown by `PostRow`
* Added error, empty, and loading state UI to `PostsList`
* Refined appearance of post and profile images in `ProfileView` and `PostRow`
* Made `MainTabView` more focused by relocating auth-related views to `AppView`, which is now the root view of the app
* Significantly reorganized and streamlined `PostsList` and `CommentsList`

### View Models
* Replaced async dispatch in `TaskViewModel` with `MainActor` attribute
* Renamed `PostData` to `PostViewModel` for consistency with other view models

### Models
* Updated `User.testUser` and `Post.testPost` to improve SwiftUI previews
* Added partial objects to `Comment` and `Post` to help simplify `CommentService` and `PostService` APIs

### Services
* Renamed `UserService` to `AuthService` for consistency with `AuthViewModel`
* Significantly refactored `AuthService`, `CommentService`, and `PostService` and refined their public APIs
* Removed no longer needed version numbering from collection references (e.g. used the `posts` collection instead of `posts_v2`)

### Utilities
* Consolidated Firestore-related utilities and extensions in new `Firestore+Extensions` file
* Relocated image upload logic from `PostService` and `AuthService` to new `Storage+Extensions` file

2021-09-15 20:14 UTC, benstone1 requested changes
Left a bunch of comments, but most are focused on style and me getting a better understanding of how things work.  Great work on this!  Love the structure that you have with it, learners are going to get a ton out of these tutorials.

Additionally, we got the updated design specs in.  You can find them at the link [here](https://drive.google.com/drive/folders/1zRJcSw3ynsHI7JjTgXmAM_2iQe-nPavb).  You should also go ahead and tweak the views so that they match closer to the designs.  Because we're not focusing as much on the UI for this skill path, you should feel free to do whatever makes the code simplest while using the design for inspiration.

2021-09-15 20:38 UTC, john-royal commented on FirebaseTestProject/Models/User.swift
> +        name: "Jamie Harris",
Glad you asked! I like using race and gender neutral names where possible, to be more inclusive. Jamie Harris is my go-to, but feel free to LMK if you have any other ideas!

2021-09-16 05:30 UTC, john-royal reviewed
Thank you for the feedback! I left some replies to answer your questions, but I’ll get to work ASAP on the requested changes.

2021-09-16 05:30 UTC, john-royal commented on FirebaseTestProject/Models/User.swift
> +        self.imageURL = imageURL
This sets the `imageURL` to `nil`. Please see my comment above.

2021-09-16 05:30 UTC, john-royal commented on FirebaseTestProject/Services/AuthService.swift
> +        let profileUpdate = result.user.createProfileChangeRequest()
Good idea! I'll make that change.

2021-09-16 05:30 UTC, john-royal commented on FirebaseTestProject/Services/CommentService.swift
>          self.user = postService.user
Nice catch! I’ll rework this.

2021-09-16 05:30 UTC, john-royal commented on FirebaseTestProject/Services/AuthService.swift
> +        id = user.uid
I thought it was cleaner this way, but now that you mention it, I think the clarity of explicitly assigning to `self` is preferable. I'll add that in.

2021-09-16 05:30 UTC, john-royal commented on FirebaseTestProject/Services/PostService.swift
> +    func fetchPosts(matching filter: PostFilter?) async throws -> [Post] {
Why? Seems a little redundant given that `fetchPosts(matching:)` with no filter parameter becomes simply `fetchPosts()`, which already exists. Am I missing something?

2021-09-16 05:30 UTC, john-royal commented on FirebaseTestProject/Services/PostService.swift
> +        async let postsTask = postsReference
Fair point! I’ll try to figure out a better solution and get back to you.

2021-09-16 05:30 UTC, john-royal commented on FirebaseTestProject/Views/CommentRow.swift
> +    struct DeleteViewModifier: ViewModifier {
Good idea! I’ll add the extension.

2021-09-16 15:00 UTC, benstone1 commented on FirebaseTestProject/Services/AuthService.swift
> +        profileUpdate.photoURL = imageURL
Haha, never mind then!  I assumed it was something that we owned.

2021-09-16 15:02 UTC, benstone1 commented on FirebaseTestProject/Services/PostService.swift
> +    func fetchPosts(matching filter: PostFilter?) async throws -> [Post] {
I guess the question is why accept a `nil` `PostFilter` at all when a `fetchPosts()` exists.

2021-09-16 15:05 UTC, benstone1 commented on FirebaseTestProject/ViewModels/PostViewModel.swift
> +    private let filter: PostFilter?
I'm good with it this way :+1:

2021-09-16 15:12 UTC, benstone1 commented on FirebaseTestProject/Views/PostsList.swift
> +    @MainActor struct RouterView: View {
Interesting, let me play around with it locally.

2021-09-16 15:13 UTC, benstone1 commented on FirebaseTestProject/Models/User.swift
> +            imageURLString = newValue?.absoluteString ?? ""
Ah, that makes sense to me.  As long as we remember to explain this context to users, this should be great then.

2021-09-16 15:13 UTC, benstone1 commented on FirebaseTestProject/Models/User.swift
> +        name: "Jamie Harris",
Jamie works for me!

2021-09-16 15:14 UTC, benstone1 commented on FirebaseTestProject/Services/AuthService.swift
> +        id = user.uid
It seems a lot handwavier in Swift 5.5, so feel free to go either way on it.

2021-09-16 15:15 UTC, benstone1 commented on FirebaseTestProject/ViewModels/CommentViewModel.swift
> +    init(commentService: CommentServiceProtocol) {
That's fair, we can leave it as is then.

2021-09-20 01:13 UTC, john-royal reviewed
I made some updates and left some replies. I’ll also update the UI, but I haven’t finished working on that yet.

I tried to address every comment you left, but some big changes include:
* Replacing the `FirestoreConvertable` protocol with Firebase’s native `Codable` support. This means [our workaround for saving user and post image URLs is no longer necessary](https://github.com/benstone1/SocialCademy/commit/8b717d8015d61a6006801ff6c9b581327a326b26#diff-2ddd49e57145415229cf3539cc302152138cec3dce7335acb160b23ed3fa6114) 🥳.
* Renaming the `Partial` object for posts and comments to `EditableFields`. Method parameter names have also been updated to `editablePost` and `editableComment`.

A few threads are still open. I left replies, but feel free to give me your thoughts whenever you’re ready!

2021-09-20 01:13 UTC, john-royal commented on FirebaseTestProject/Services/AuthService.swift
> +        let profileUpdate = result.user.createProfileChangeRequest()
I agree with the spirit of this suggestion, but I tried changing it to `profileUpdateRequest` and found the result to be a bit verbose:
```swift
let profileUpdateRequest = result.user.createProfileChangeRequest()
profileUpdateRequest.displayName = name
try await profileUpdateRequest.commitChanges()
```
That’s why I instead renamed the variable `changeRequest`. This was [used in Firebase’s official sample projects](https://github.com/firebase/quickstart-ios/blob/c59bf0e8eb70582085282c90e835fa770146e948/authentication/AuthenticationExample/ViewControllers/UserViewController.swift#L145), and I thought it struck a good balance between clarity and concision. What do you think?

2021-09-20 01:13 UTC, john-royal commented on FirebaseTestProject/Services/AuthService.swift
> +        let profileUpdate = user.createProfileChangeRequest()
I renamed it to `changeRequest`. Please see the note above.

2021-09-20 15:51 UTC, benstone1 commented on FirebaseTestProject/Models/Comment.swift
> +    struct Partial {
Yeah, I think that name works :+1:

2021-09-20 20:53 UTC, merged